/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrescricoesRouteImport } from './routes/prescricoes'
import { Route as DefinicoesRouteImport } from './routes/definicoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppV2RouteImport } from './routes/app-v2'
import { Route as AppRouteImport } from './routes/app'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtentesUtenteIdRouteImport } from './routes/utentes.$utenteId'
import { Route as ConsultaEventoIdRouteImport } from './routes/consulta.$eventoId'

const PrescricoesRoute = PrescricoesRouteImport.update({
  id: '/prescricoes',
  path: '/prescricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinicoesRoute = DefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppV2Route = AppV2RouteImport.update({
  id: '/app-v2',
  path: '/app-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtentesUtenteIdRoute = UtentesUtenteIdRouteImport.update({
  id: '/utentes/$utenteId',
  path: '/utentes/$utenteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaEventoIdRoute = ConsultaEventoIdRouteImport.update({
  id: '/consulta/$eventoId',
  path: '/consulta/$eventoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/app': typeof AppRoute
  '/app-v2': typeof AppV2Route
  '/auth': typeof AuthRoute
  '/definicoes': typeof DefinicoesRoute
  '/prescricoes': typeof PrescricoesRoute
  '/consulta/$eventoId': typeof ConsultaEventoIdRoute
  '/utentes/$utenteId': typeof UtentesUtenteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/app': typeof AppRoute
  '/app-v2': typeof AppV2Route
  '/auth': typeof AuthRoute
  '/definicoes': typeof DefinicoesRoute
  '/prescricoes': typeof PrescricoesRoute
  '/consulta/$eventoId': typeof ConsultaEventoIdRoute
  '/utentes/$utenteId': typeof UtentesUtenteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/app': typeof AppRoute
  '/app-v2': typeof AppV2Route
  '/auth': typeof AuthRoute
  '/definicoes': typeof DefinicoesRoute
  '/prescricoes': typeof PrescricoesRoute
  '/consulta/$eventoId': typeof ConsultaEventoIdRoute
  '/utentes/$utenteId': typeof UtentesUtenteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/app'
    | '/app-v2'
    | '/auth'
    | '/definicoes'
    | '/prescricoes'
    | '/consulta/$eventoId'
    | '/utentes/$utenteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/app'
    | '/app-v2'
    | '/auth'
    | '/definicoes'
    | '/prescricoes'
    | '/consulta/$eventoId'
    | '/utentes/$utenteId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/app'
    | '/app-v2'
    | '/auth'
    | '/definicoes'
    | '/prescricoes'
    | '/consulta/$eventoId'
    | '/utentes/$utenteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AppRoute: typeof AppRoute
  AppV2Route: typeof AppV2Route
  AuthRoute: typeof AuthRoute
  DefinicoesRoute: typeof DefinicoesRoute
  PrescricoesRoute: typeof PrescricoesRoute
  ConsultaEventoIdRoute: typeof ConsultaEventoIdRoute
  UtentesUtenteIdRoute: typeof UtentesUtenteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prescricoes': {
      id: '/prescricoes'
      path: '/prescricoes'
      fullPath: '/prescricoes'
      preLoaderRoute: typeof PrescricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definicoes': {
      id: '/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof DefinicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-v2': {
      id: '/app-v2'
      path: '/app-v2'
      fullPath: '/app-v2'
      preLoaderRoute: typeof AppV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utentes/$utenteId': {
      id: '/utentes/$utenteId'
      path: '/utentes/$utenteId'
      fullPath: '/utentes/$utenteId'
      preLoaderRoute: typeof UtentesUtenteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta/$eventoId': {
      id: '/consulta/$eventoId'
      path: '/consulta/$eventoId'
      fullPath: '/consulta/$eventoId'
      preLoaderRoute: typeof ConsultaEventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AppRoute: AppRoute,
  AppV2Route: AppV2Route,
  AuthRoute: AuthRoute,
  DefinicoesRoute: DefinicoesRoute,
  PrescricoesRoute: PrescricoesRoute,
  ConsultaEventoIdRoute: ConsultaEventoIdRoute,
  UtentesUtenteIdRoute: UtentesUtenteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
