/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrescricoesRouteImport } from './routes/prescricoes'
import { Route as AppRouteImport } from './routes/app'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtentesUtenteIdRouteImport } from './routes/utentes.$utenteId'

const PrescricoesRoute = PrescricoesRouteImport.update({
  id: '/prescricoes',
  path: '/prescricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtentesUtenteIdRoute = UtentesUtenteIdRouteImport.update({
  id: '/utentes/$utenteId',
  path: '/utentes/$utenteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/app': typeof AppRoute
  '/prescricoes': typeof PrescricoesRoute
  '/utentes/$utenteId': typeof UtentesUtenteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/app': typeof AppRoute
  '/prescricoes': typeof PrescricoesRoute
  '/utentes/$utenteId': typeof UtentesUtenteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/app': typeof AppRoute
  '/prescricoes': typeof PrescricoesRoute
  '/utentes/$utenteId': typeof UtentesUtenteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agenda' | '/app' | '/prescricoes' | '/utentes/$utenteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agenda' | '/app' | '/prescricoes' | '/utentes/$utenteId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/app'
    | '/prescricoes'
    | '/utentes/$utenteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AppRoute: typeof AppRoute
  PrescricoesRoute: typeof PrescricoesRoute
  UtentesUtenteIdRoute: typeof UtentesUtenteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prescricoes': {
      id: '/prescricoes'
      path: '/prescricoes'
      fullPath: '/prescricoes'
      preLoaderRoute: typeof PrescricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utentes/$utenteId': {
      id: '/utentes/$utenteId'
      path: '/utentes/$utenteId'
      fullPath: '/utentes/$utenteId'
      preLoaderRoute: typeof UtentesUtenteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AppRoute: AppRoute,
  PrescricoesRoute: PrescricoesRoute,
  UtentesUtenteIdRoute: UtentesUtenteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
